// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");
var Square$ReactHooksTemplate = require("./Square.bs.js");

function Board(Props) {
  var onClick = Props.onClick;
  return Belt_Array.map(/* array */[
              0,
              1,
              2
            ], (function (row) {
                return React.createElement("div", {
                            key: String(row),
                            className: "board-row"
                          }, Belt_Array.map(/* array */[
                                0,
                                1,
                                2
                              ], (function (col) {
                                  var squareIndex = Caml_int32.imul(3, row) + col | 0;
                                  return React.createElement(Square$ReactHooksTemplate.make, {
                                              onClick: (function (evt) {
                                                  return Curry._2(onClick, evt, squareIndex);
                                                }),
                                              key: String(squareIndex)
                                            });
                                })));
              }));
}

var make = Board;

exports.make = make;
/* react Not a pure module */
